# 64-bit primary zygote with 32-bit app support (arm64-v8a,armeabi-v7a,armeabi)
$(call inherit-product, $(SRC_TARGET_DIR)/product/core_64_bit.mk)

$(call inherit-product, device/gpd/xdplus/xdplus.mk)

# Common CM stuff. SIM-less tablet: common_full (non-telephony) instead of
# common_full_phone, which drops LineageOS telephony.mk (messaging, Stk, apns,
# sensitive_pn). Re-add the two non-telephony things common_full_phone carried:
# the LatinIME keyboard + its dictionaries.
$(call inherit-product, vendor/lineage/config/common_full.mk)
PRODUCT_PACKAGES += LatinIME
PRODUCT_PACKAGE_OVERLAYS += vendor/lineage/overlay/dictionaries
PRODUCT_ENFORCE_RRO_EXCLUDED_OVERLAYS += vendor/lineage/overlay/dictionaries

# No BUILD_FINGERPRINT / PRIVATE_BUILD_DESC override. The build emits its own
# fingerprint from PRODUCT_BRAND/PRODUCT_DEVICE/BUILD_ID/BUILD_NUMBER, which is
# the honest one and already what ro.system.build.fingerprint carries:
#
#   GPD/lineage_xdplus/xdplus:11/RQ3A.211001.001/<YYYYMMDD.HHMMSS>:userdebug/dev-keys
#
# An override used to pin both props to the upstream tree this port was derived
# from. That is someone else's build identity on our images — the vendor base is
# ours — so it is gone. Do not reintroduce a hardcoded fingerprint here: if a
# vendor blob or DRM path is ever found to need one, fix the blob or document the
# dependency, do not relabel the build as a third party's.

PRODUCT_NAME := lineage_xdplus
PRODUCT_DEVICE := xdplus
PRODUCT_BRAND := GPD
PRODUCT_MANUFACTURER := GPD
PRODUCT_MODEL := xdplus

PRODUCT_BUILD_PROP_OVERRIDES += \
    PRODUCT_DEVICE="xdplus"

# Release signing. Sign the platform with our own keys (device/gpd/xdplus/keys/,
# generated by development/tools/make_key) instead of the public AOSP test-keys,
# so ro.build.tags flips test-keys -> release-keys and the "signed with public
# keys" warning goes away (Play Protect / platform-signature based). OTA public
# key = releasekey so the Updater's RecoverySystem.verifyPackage accepts our
# self-signed OTA zips (see docs/OTA_HOSTING.md).
# NOTE: BUILD_FINGERPRINT above intentionally keeps its ".../test-keys" text — it
# is matched to the ALLDOCUBE 8.1 vendor base for DRM/Widevine provisioning and is
# a separate prop from ro.build.tags; do not flip it or L3 provisioning may break.
PRODUCT_DEFAULT_DEV_CERTIFICATE := device/gpd/xdplus/keys/releasekey
PRODUCT_OTA_PUBLIC_KEYS := device/gpd/xdplus/keys/releasekey

# Drop the AOSP Camera2 app (camera-less device). It's inherited from
# handheld_product.mk (via full_base); AOSP defers product inheritance so a
# $(filter-out) here is a no-op. The reliable removal is an installed override
# package (device/gpd/xdplus/removed_apps) that LOCAL_OVERRIDES_PACKAGES Camera2.
# Gallery2 is kept (screenshots / photo viewing).
PRODUCT_PACKAGES += xdplusRemovedApps
