# 64-bit primary zygote with 32-bit app support (arm64-v8a,armeabi-v7a,armeabi)
$(call inherit-product, $(SRC_TARGET_DIR)/product/core_64_bit.mk)

$(call inherit-product, device/gpd/xdplus/xdplus.mk)

# Common CM stuff. SIM-less tablet: common_full (non-telephony) instead of
# common_full_phone, which drops LineageOS telephony.mk (messaging, Stk, apns,
# sensitive_pn). Re-add the two non-telephony things common_full_phone carried:
# the LatinIME keyboard + its dictionaries.
$(call inherit-product, vendor/lineage/config/common_full.mk)
PRODUCT_PACKAGES += LatinIME
PRODUCT_PACKAGE_OVERLAYS += vendor/lineage/overlay/dictionaries
PRODUCT_ENFORCE_RRO_EXCLUDED_OVERLAYS += vendor/lineage/overlay/dictionaries

# Match the shipped Android 11 build fingerprint (ALLDOCUBE U1005E 8.1 vendor base)

# ro.build.version.base_os (Athena "Base OS" was empty). PLATFORM_BASE_OS is the
# only clean source for this prop — adding ro.build.version.base_os via
# PRODUCT_PROPERTY_OVERRIDES collides with the build-generated key. Set it to our
# own fingerprint (the OS this security-patch baseline is built from == this build).

PRODUCT_NAME := lineage_xdplus
PRODUCT_DEVICE := xdplus
PRODUCT_BRAND := GPD
PRODUCT_MANUFACTURER := GPD
PRODUCT_MODEL := xdplus

PRODUCT_BUILD_PROP_OVERRIDES += \
    PRODUCT_DEVICE="xdplus"

# Release signing. Sign the platform with our own keys (device/gpd/xdplus/keys/,
# generated by development/tools/make_key) instead of the public AOSP test-keys,
# so ro.build.tags flips test-keys -> release-keys and the "signed with public
# keys" warning goes away (Play Protect / platform-signature based). OTA public
# key = releasekey so the Updater's RecoverySystem.verifyPackage accepts our
# self-signed OTA zips (see docs/OTA_HOSTING.md).
# NOTE: BUILD_FINGERPRINT above intentionally keeps its ".../test-keys" text — it
# is matched to the ALLDOCUBE 8.1 vendor base for DRM/Widevine provisioning and is
# a separate prop from ro.build.tags; do not flip it or L3 provisioning may break.
PRODUCT_DEFAULT_DEV_CERTIFICATE := device/gpd/xdplus/keys/releasekey
PRODUCT_OTA_PUBLIC_KEYS := device/gpd/xdplus/keys/releasekey

# Drop the AOSP Camera2 app (camera-less device). It's inherited from
# handheld_product.mk (via full_base); AOSP defers product inheritance so a
# $(filter-out) here is a no-op. The reliable removal is an installed override
# package (device/gpd/xdplus/removed_apps) that LOCAL_OVERRIDES_PACKAGES Camera2.
# Gallery2 is kept (screenshots / photo viewing).
PRODUCT_PACKAGES += xdplusRemovedApps
